#!/bin/bash

# Evaluate the status of a file
#

test_file(){
FILE=~/.bashrc

if [ -e "$FILE" ]; then
	if [ -f "$FILE" ]; then
		echo "$FILE is a regular file"
	fi
	if [ -d "$FILE" ]; then
		echo "$FILE is a directory"
	fi
	if [ -r "$FILE" ]; then
		echo "$FILE is readable"
	fi
	if [ -w "$FILE" ]; then
		echo "$FILE is writable"
	fi
	if [ -x "$FILE" ]; then
		echo "$FILE is exicutable/searchable"
	fi
else
	echo "hello $FILE does not exit"
	return 1
fi
}
test_file
