#!/bin/bash

# test-integer: evaluate the value of an integer.

echo "What INT in your mind ? <> "
read INT

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	if (( INT == 0 )); then
		echo "INT is Zero"
	else
		if (( INT < 0 )); then
			echo "INT is negative"
		else
			echo "INT is positive"
		fi
		if (( (( INT % 2 )) == 0 )); then
			echo "INT is even"
		else
			echo "INT is odd"
		fi
	fi
else
	echo "INT is not integer"
	exit 1
fi
