#!/bin/bash
#
# test integer: determine if an integer is within specified range

MIN_VAL=1
MAX_VAL=100
echo "What integer in your mind"
read INT

if [[ "$INT" =~ ^-?[0-9]+$ ]]; then
	if  (( INT >= MIN_VAL )) && (( INT <= MAX_VAL )); then
		echo "$INT is within $MIN_VAL to $MAX_VAL"
	else
		echo "$INT is out of range"
	fi
else
	echo "INT is not an integer"
	exit 1
fi

