#!/bin/bash

# program to output a system information page

TITLE="System Information Report for $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIME_STEMP="Generated $CURRENT_TIME by $USER"

report_uptime (){
	cat << _EOF_
		<h2>System Uptime</h2>
		<pre>$(uptime)</pre>
_EOF_
	return
}
report_disk_space (){
	cat << _EOF_
		<h2>System Disk Space</h2>
		<pre>$(df -h)</pre>
_EOF_
	return
}
report_home_space (){
	cat << _EOF_
		<h2>System Home Space</h2>
		<pre>$(du -sh /home/*)</pre>
_EOF_
	return
}


cat << _EOF_
<html>
	<head>
		<title>$TITLE</title>
	</head>
	<body>
		<h1>$TITLE</h1>
		<p>$TIME_STEMP</p>
		$(report_uptime)
		$(report_disk_space)
		$(report_home_space)
	</body>
</html>
_EOF_

